<?php

namespace Database\Seeders;

use App\Models\ChartOfAccount;
use Illuminate\Database\Seeder;

class ChartOfAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            // ASSETS (1000-1999)
            [
                'account_code' => '1000',
                'account_name' => 'ASSETS',
                'description' => 'All company assets',
                'account_type' => 'ASSET',
                'account_subtype' => 'CURRENT_ASSET',
                'normal_balance' => 'DEBIT',
                'level' => 1,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1100',
                'account_name' => 'Current Assets',
                'description' => 'Assets expected to be converted to cash within one year',
                'account_type' => 'ASSET',
                'account_subtype' => 'CURRENT_ASSET',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1110',
                'account_name' => 'Cash',
                'description' => 'Cash on hand and in bank',
                'account_type' => 'ASSET',
                'account_subtype' => 'CASH',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1120',
                'account_name' => 'Accounts Receivable',
                'description' => 'Amounts owed by customers',
                'account_type' => 'ASSET',
                'account_subtype' => 'ACCOUNTS_RECEIVABLE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1130',
                'account_name' => 'Particulars Inventory',
                'description' => 'Raw particulars materials inventory',
                'account_type' => 'ASSET',
                'account_subtype' => 'INVENTORY',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1140',
                'account_name' => 'Finished Goods Inventory',
                'description' => 'Processed and finished stone products',
                'account_type' => 'ASSET',
                'account_subtype' => 'INVENTORY',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1150',
                'account_name' => 'Work in Progress',
                'description' => 'Particulars materials in production process',
                'account_type' => 'ASSET',
                'account_subtype' => 'INVENTORY',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1200',
                'account_name' => 'Fixed Assets',
                'description' => 'Long-term assets used in business operations',
                'account_type' => 'ASSET',
                'account_subtype' => 'FIXED_ASSET',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1210',
                'account_name' => 'Machinery & Equipment',
                'description' => 'Cutting, polishing, and processing machinery',
                'account_type' => 'ASSET',
                'account_subtype' => 'FIXED_ASSET',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '1220',
                'account_name' => 'Vehicles',
                'description' => 'Company vehicles for transportation',
                'account_type' => 'ASSET',
                'account_subtype' => 'FIXED_ASSET',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],

            // LIABILITIES (2000-2999)
            [
                'account_code' => '2000',
                'account_name' => 'LIABILITIES',
                'description' => 'All company liabilities',
                'account_type' => 'LIABILITY',
                'account_subtype' => 'CURRENT_LIABILITY',
                'normal_balance' => 'CREDIT',
                'level' => 1,
                'is_system_account' => true,
            ],
            [
                'account_code' => '2100',
                'account_name' => 'Current Liabilities',
                'description' => 'Liabilities due within one year',
                'account_type' => 'LIABILITY',
                'account_subtype' => 'CURRENT_LIABILITY',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '2110',
                'account_name' => 'Accounts Payable',
                'description' => 'Amounts owed to suppliers and vendors',
                'account_type' => 'LIABILITY',
                'account_subtype' => 'ACCOUNTS_PAYABLE',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '2120',
                'account_name' => 'Accrued Expenses',
                'description' => 'Expenses incurred but not yet paid',
                'account_type' => 'LIABILITY',
                'account_subtype' => 'CURRENT_LIABILITY',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],

            // EQUITY (3000-3999)
            [
                'account_code' => '3000',
                'account_name' => 'OWNER\'S EQUITY',
                'description' => 'Owner\'s investment and retained earnings',
                'account_type' => 'EQUITY',
                'account_subtype' => 'OWNER_EQUITY',
                'normal_balance' => 'CREDIT',
                'level' => 1,
                'is_system_account' => true,
            ],
            [
                'account_code' => '3100',
                'account_name' => 'Owner\'s Capital',
                'description' => 'Initial investment by owner',
                'account_type' => 'EQUITY',
                'account_subtype' => 'CAPITAL',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '3200',
                'account_name' => 'Retained Earnings',
                'description' => 'Accumulated profits retained in business',
                'account_type' => 'EQUITY',
                'account_subtype' => 'RETAINED_EARNINGS',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],

            // REVENUE (4000-4999)
            [
                'account_code' => '4000',
                'account_name' => 'REVENUE',
                'description' => 'All income and revenue accounts',
                'account_type' => 'REVENUE',
                'account_subtype' => 'SALES_REVENUE',
                'normal_balance' => 'CREDIT',
                'level' => 1,
                'is_system_account' => true,
            ],
            [
                'account_code' => '4100',
                'account_name' => 'Particulars Sales Revenue',
                'description' => 'Revenue from particulars product sales',
                'account_type' => 'REVENUE',
                'account_subtype' => 'SALES_REVENUE',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '4200',
                'account_name' => 'Processing Services Revenue',
                'description' => 'Revenue from stone processing services',
                'account_type' => 'REVENUE',
                'account_subtype' => 'SERVICE_REVENUE',
                'normal_balance' => 'CREDIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],

            // EXPENSES (5000-5999)
            [
                'account_code' => '5000',
                'account_name' => 'EXPENSES',
                'description' => 'All expense accounts',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'OPERATING_EXPENSE',
                'normal_balance' => 'DEBIT',
                'level' => 1,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5100',
                'account_name' => 'Cost of Goods Sold',
                'description' => 'Direct costs of stone materials sold',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'COST_OF_GOODS_SOLD',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5200',
                'account_name' => 'Operating Expenses',
                'description' => 'General business operating expenses',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'OPERATING_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5210',
                'account_name' => 'Labor Costs',
                'description' => 'Employee wages and benefits',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'OPERATING_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5220',
                'account_name' => 'Machinery Maintenance',
                'description' => 'Maintenance and repair of equipment',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'OPERATING_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5230',
                'account_name' => 'Utilities',
                'description' => 'Electricity, water, and other utilities',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'OPERATING_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5300',
                'account_name' => 'Administrative Expenses',
                'description' => 'General administrative costs',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'ADMINISTRATIVE_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 2,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5310',
                'account_name' => 'Office Supplies',
                'description' => 'Office supplies and materials',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'ADMINISTRATIVE_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
            [
                'account_code' => '5320',
                'account_name' => 'Professional Fees',
                'description' => 'Legal, accounting, and consulting fees',
                'account_type' => 'EXPENSE',
                'account_subtype' => 'ADMINISTRATIVE_EXPENSE',
                'normal_balance' => 'DEBIT',
                'parent_account_id' => null,
                'level' => 3,
                'is_system_account' => true,
            ],
        ];

        foreach ($accounts as $accountData) {
            ChartOfAccount::create($accountData);
        }
    }
}
